name: StaffUtilities
version: '${version}'
main: me.notro.staffutilities.StaffUtilities
api-version: '1.20'
authors: [ Notro ]
description: An helpful Staff Tools for every Minecraft server.

commands:
  staffmode:
    aliases: sm
    description: Toggle staff mode command.

  staffchat:
    aliases: sc
    description: Enable/Disable staff chat for discussion with the other staff.

  report:
    description: Report a player.

  reports:
    description: A Staff reports manager. Clear reports on a certain player or clear all reports.

  punish:
    description: Punish a member.